micronaut:
  application:
    name: noticeBoard
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
netty:
  default:
    allocator:
      max-order: 3
